In [3]:
from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("WordCount") \
    .getOrCreate()

print("Spark berhasil dijalankan!")
print("Versi Spark:", spark.version)

Spark berhasil dijalankan!
Versi Spark: 4.0.4

In [4]:
data = [1, 2, 3, 4, 5]

rdd = spark.sparkContext.parallelize(data)

print("Data RDD:", rdd.collect())
print("Jumlah data:", rdd.count())

Data RDD: [1, 2, 3, 4, 5]
Jumlah data: 5

## Persiapan Dataset

Dataset yang digunakan berupa data teks dengan jumlah 6.000 baris.
Dataset ini digunakan untuk melakukan pengujian WordCount menggunakan PySpark.

In [5]:
# Membuat dataset teks untuk praktikum WordCount
# Dataset terdiri dari 6.000 baris bertema Big Data dan Apache Spark

data_teks = [
    "teknologi big data membantu pengolahan informasi dalam jumlah yang sangat besar",
    "apache spark digunakan untuk menjalankan proses analisis data secara lebih efisien",
    "pyspark memungkinkan pemrograman spark dilakukan menggunakan bahasa python",
    "pemrosesan paralel membagi pekerjaan agar beberapa bagian dapat berjalan bersamaan",
    "dataset berukuran besar dapat dibagi menjadi beberapa partition untuk diproses",
    "setiap partition dapat dikerjakan secara independen oleh proses yang berbeda",
    "spark memanfaatkan sumber daya komputasi untuk mempercepat pengolahan data",
    "wordcount merupakan metode sederhana untuk menghitung jumlah kemunculan sebuah kata",
    "data teks perlu dipersiapkan terlebih dahulu sebelum dilakukan proses analisis",
    "perubahan huruf menjadi lowercase membantu menyamakan bentuk kata pada dataset",
    "flatmap dapat memisahkan sebuah kalimat menjadi kumpulan kata yang lebih kecil",
    "fungsi map dapat membentuk pasangan antara kata dengan nilai satu",
    "reducebykey menggabungkan nilai dari kata yang memiliki key yang sama",
    "transformation pada spark membentuk tahapan proses tanpa langsung menjalankannya",
    "action menjadi pemicu agar rangkaian pemrosesan spark mulai dieksekusi",
    "lazy evaluation membantu spark menyusun proses komputasi dengan lebih efisien",
    "jumlah partition dapat memberikan pengaruh terhadap waktu pemrosesan sebuah dataset",
    "partition yang terlalu sedikit dapat membuat sumber daya komputasi kurang dimanfaatkan",
    "partition yang terlalu banyak dapat menambah overhead selama proses berlangsung",
    "shuffle terjadi ketika data dengan key yang sama perlu dipindahkan dan dikelompokkan",
    "proses shuffle dapat menjadi salah satu bottleneck dalam pengolahan data terdistribusi",
    "worker menjalankan task untuk mengolah bagian data yang telah dibagikan oleh spark",
    "sebuah spark job dapat terdiri dari beberapa stage selama proses pemrosesan berlangsung",
    "setiap stage memiliki sejumlah task yang dapat dijalankan secara paralel",
    "hasil pengolahan wordcount dapat digunakan untuk mengetahui kata yang sering muncul"
]

with open("bigdata.txt", "w", encoding="utf-8") as file:
    for i in range(6000):
        file.write(data_teks[i % len(data_teks)] + "\n")

print("Dataset WordCount berhasil dibuat.")
print("Target jumlah data: 6000 baris")

Dataset WordCount berhasil dibuat.
Target jumlah data: 6000 baris

In [7]:
# Memeriksa jumlah baris pada dataset

nama_file_dataset = "bigdata.txt"

with open(nama_file_dataset, "r", encoding="utf-8") as dataset:
    total_baris = sum(1 for _ in dataset)

print("Nama dataset :", nama_file_dataset)
print("Jumlah baris :", total_baris)

if total_baris >= 5000:
    print("Status       : Dataset memenuhi ketentuan tugas.")
else:
    print("Status       : Dataset belum memenuhi ketentuan tugas.")

Nama dataset : bigdata.txt
Jumlah baris : 6000
Status       : Dataset memenuhi ketentuan tugas.

In [12]:
# Menampilkan beberapa contoh isi dataset

nama_file_dataset = "bigdata.txt"
jumlah_sampel = 10

print("Contoh isi dataset:\n")

with open(nama_file_dataset, "r", encoding="utf-8") as dataset:
    for nomor in range(1, jumlah_sampel + 1):
        isi_baris = dataset.readline().strip()
        print(f"{nomor}. {isi_baris}")

Contoh isi dataset:

1. teknologi big data membantu pengolahan informasi dalam jumlah yang sangat besar
2. apache spark digunakan untuk menjalankan proses analisis data secara lebih efisien
3. pyspark memungkinkan pemrograman spark dilakukan menggunakan bahasa python
4. pemrosesan paralel membagi pekerjaan agar beberapa bagian dapat berjalan bersamaan
5. dataset berukuran besar dapat dibagi menjadi beberapa partition untuk diproses
6. setiap partition dapat dikerjakan secara independen oleh proses yang berbeda
7. spark memanfaatkan sumber daya komputasi untuk mempercepat pengolahan data
8. wordcount merupakan metode sederhana untuk menghitung jumlah kemunculan sebuah kata
9. data teks perlu dipersiapkan terlebih dahulu sebelum dilakukan proses analisis
10. perubahan huruf menjadi lowercase membantu menyamakan bentuk kata pada dataset

In [13]:
# Memastikan file dataset tersedia di lingkungan Google Colab

import os

lokasi_dataset = "bigdata.txt"

if os.path.exists(lokasi_dataset):
    ukuran_file = os.path.getsize(lokasi_dataset)

    print("Status file   : Ditemukan")
    print("Nama file     :", lokasi_dataset)
    print("Ukuran file   :", ukuran_file, "bytes")
    print("Dataset siap digunakan oleh PySpark.")
else:
    print("Status file   : Tidak ditemukan")

Status file   : Ditemukan
Nama file     : bigdata.txt
Ukuran file   : 477600 bytes
Dataset siap digunakan oleh PySpark.

## Pemrosesan Dataset Menggunakan PySpark

Pada tahap ini dataset dibaca menggunakan RDD PySpark.
Data kemudian akan dipersiapkan untuk proses preprocessing dan WordCount.

In [3]:
# Mengaktifkan kembali SparkSession

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("WordCount_BigData") \
    .getOrCreate()

print("SparkSession berhasil diaktifkan.")
print("Versi Spark :", spark.version)

SparkSession berhasil diaktifkan.
Versi Spark : 4.0.4

In [4]:
# Membaca dataset menggunakan PySpark RDD

sumber_data = "bigdata.txt"

rdd_teks = spark.sparkContext.textFile(sumber_data)

print("Dataset berhasil dibaca menggunakan PySpark.")

Dataset berhasil dibaca menggunakan PySpark.

In [8]:
# Menghitung jumlah baris dataset melalui RDD

total_data_spark = rdd_teks.count()

print("Jumlah baris yang dibaca PySpark :", total_data_spark)

Jumlah baris yang dibaca PySpark : 6000

In [9]:
# Mengambil 5 contoh baris dari RDD

contoh_data_spark = rdd_teks.take(5)

print("Contoh data yang dibaca PySpark:\n")

for nomor, baris in enumerate(contoh_data_spark, start=1):
    print(f"{nomor}. {baris}")

Contoh data yang dibaca PySpark:

1. teknologi big data membantu pengolahan informasi dalam jumlah yang sangat besar
2. apache spark digunakan untuk menjalankan proses analisis data secara lebih efisien
3. pyspark memungkinkan pemrograman spark dilakukan menggunakan bahasa python
4. pemrosesan paralel membagi pekerjaan agar beberapa bagian dapat berjalan bersamaan
5. dataset berukuran besar dapat dibagi menjadi beberapa partition untuk diproses

In [10]:
# Melihat jumlah partition awal pada RDD

partition_awal = rdd_teks.getNumPartitions()

print("Jumlah partition awal :", partition_awal)

Jumlah partition awal : 2

In [12]:
# Fungsi preprocessing untuk membersihkan setiap baris teks

import re

def bersihkan_teks(teks):
    teks = teks.lower()
    teks = re.sub(r"[^a-z0-9\s]", " ", teks)
    teks = re.sub(r"\s+", " ", teks).strip()
    return teks

In [13]:
# Menerapkan preprocessing pada seluruh dataset

rdd_bersih = rdd_teks.map(bersihkan_teks)

print("Proses preprocessing berhasil didefinisikan.")

Proses preprocessing berhasil didefinisikan.

In [14]:
# Menampilkan 5 contoh data setelah preprocessing

contoh_data_bersih = rdd_bersih.take(5)

print("Contoh data setelah preprocessing:\n")

for nomor, teks in enumerate(contoh_data_bersih, start=1):
    print(f"{nomor}. {teks}")

Contoh data setelah preprocessing:

1. teknologi big data membantu pengolahan informasi dalam jumlah yang sangat besar
2. apache spark digunakan untuk menjalankan proses analisis data secara lebih efisien
3. pyspark memungkinkan pemrograman spark dilakukan menggunakan bahasa python
4. pemrosesan paralel membagi pekerjaan agar beberapa bagian dapat berjalan bersamaan
5. dataset berukuran besar dapat dibagi menjadi beberapa partition untuk diproses

In [15]:
# Memastikan jumlah data tetap sama setelah preprocessing

jumlah_setelah_preprocessing = rdd_bersih.count()

print("Jumlah data sebelum preprocessing :", total_data_spark)
print("Jumlah data setelah preprocessing :", jumlah_setelah_preprocessing)

Jumlah data sebelum preprocessing : 6000
Jumlah data setelah preprocessing : 6000

In [16]:
# Memecah setiap baris teks menjadi kata-kata individual

rdd_kumpulan_kata = rdd_bersih.flatMap(
    lambda baris_teks: baris_teks.split()
)

print("Proses tokenisasi dengan flatMap() berhasil didefinisikan.")

Proses tokenisasi dengan flatMap() berhasil didefinisikan.

In [17]:
# Menampilkan 20 kata pertama hasil tokenisasi

contoh_kata = rdd_kumpulan_kata.take(20)

print("20 kata pertama setelah tokenisasi:\n")

for nomor, kata in enumerate(contoh_kata, start=1):
    print(f"{nomor}. {kata}")

20 kata pertama setelah tokenisasi:

1. teknologi
2. big
3. data
4. membantu
5. pengolahan
6. informasi
7. dalam
8. jumlah
9. yang
10. sangat
11. besar
12. apache
13. spark
14. digunakan
15. untuk
16. menjalankan
17. proses
18. analisis
19. data
20. secara

In [18]:
# Menghitung total kata pada seluruh dataset

total_kata_dataset = rdd_kumpulan_kata.count()

print("Jumlah baris dataset :", jumlah_setelah_preprocessing)
print("Total kata dataset   :", total_kata_dataset)

Jumlah baris dataset : 6000
Total kata dataset   : 61680

In [19]:
# Memeriksa apakah terdapat token kosong setelah proses pemisahan kata

jumlah_kata_kosong = rdd_kumpulan_kata.filter(
    lambda kata: kata.strip() == ""
).count()

print("Jumlah token kosong :", jumlah_kata_kosong)

if jumlah_kata_kosong == 0:
    print("Status              : Tokenisasi bersih dan siap untuk WordCount.")
else:
    print("Status              : Masih terdapat token kosong.")

Jumlah token kosong : 0
Status              : Tokenisasi bersih dan siap untuk WordCount.

In [20]:
# Mengubah setiap kata menjadi pasangan (kata, 1)

rdd_pasangan_kata = rdd_kumpulan_kata.map(
    lambda kata: (kata, 1)
)

print("Pembentukan pasangan (kata, 1) berhasil didefinisikan.")

Pembentukan pasangan (kata, 1) berhasil didefinisikan.

In [21]:
# Menampilkan 15 pasangan kata pertama

contoh_pasangan = rdd_pasangan_kata.take(15)

print("Contoh pasangan (kata, 1):\n")

for nomor, pasangan in enumerate(contoh_pasangan, start=1):
    print(f"{nomor}. {pasangan}")

Contoh pasangan (kata, 1):

1. ('teknologi', 1)
2. ('big', 1)
3. ('data', 1)
4. ('membantu', 1)
5. ('pengolahan', 1)
6. ('informasi', 1)
7. ('dalam', 1)
8. ('jumlah', 1)
9. ('yang', 1)
10. ('sangat', 1)
11. ('besar', 1)
12. ('apache', 1)
13. ('spark', 1)
14. ('digunakan', 1)
15. ('untuk', 1)

In [22]:
# Memastikan setiap kata telah berubah menjadi satu pasangan (kata, 1)

total_pasangan_kata = rdd_pasangan_kata.count()

print("Total kata sebelum map() :", total_kata_dataset)
print("Total pasangan setelah map() :", total_pasangan_kata)

if total_pasangan_kata == total_kata_dataset:
    print("Status : Setiap kata berhasil diubah menjadi pasangan (kata, 1).")
else:
    print("Status : Terdapat perbedaan jumlah data.")

Total kata sebelum map() : 61680
Total pasangan setelah map() : 61680
Status : Setiap kata berhasil diubah menjadi pasangan (kata, 1).

In [23]:
# Menghitung frekuensi setiap kata menggunakan reduceByKey()

rdd_frekuensi_kata = rdd_pasangan_kata.reduceByKey(
    lambda nilai_a, nilai_b: nilai_a + nilai_b
)

print("Proses WordCount dengan reduceByKey() berhasil didefinisikan.")

Proses WordCount dengan reduceByKey() berhasil didefinisikan.

In [24]:
# Menampilkan 15 hasil WordCount pertama

contoh_hasil_wordcount = rdd_frekuensi_kata.take(15)

print("Contoh hasil WordCount:\n")

for nomor, hasil in enumerate(contoh_hasil_wordcount, start=1):
    print(f"{nomor}. {hasil[0]} = {hasil[1]}")

Contoh hasil WordCount:

1. teknologi = 240
2. big = 240
3. membantu = 720
4. informasi = 240
5. besar = 480
6. apache = 240
7. digunakan = 480
8. menjalankan = 480
9. memungkinkan = 240
10. dilakukan = 480
11. menggunakan = 240
12. python = 240
13. pemrosesan = 960
14. paralel = 480
15. pekerjaan = 240

In [25]:
# Menghitung jumlah kata unik

jumlah_kata_unik = rdd_frekuensi_kata.count()

print("Total kata dalam dataset :", total_kata_dataset)
print("Jumlah kata unik         :", jumlah_kata_unik)

Total kata dalam dataset : 61680
Jumlah kata unik         : 143

In [26]:
# Memastikan total hasil WordCount sama dengan total kata awal

total_frekuensi = rdd_frekuensi_kata.map(
    lambda pasangan: pasangan[1]
).sum()

print("Total kata hasil tokenisasi :", total_kata_dataset)
print("Total frekuensi WordCount   :", total_frekuensi)

if total_frekuensi == total_kata_dataset:
    print("Status : Hasil WordCount berhasil diverifikasi.")
else:
    print("Status : Terdapat ketidaksesuaian hasil.")

Total kata hasil tokenisasi : 61680
Total frekuensi WordCount   : 61680
Status : Hasil WordCount berhasil diverifikasi.

In [27]:
# Mengurutkan hasil WordCount berdasarkan frekuensi tertinggi

rdd_kata_terurut = rdd_frekuensi_kata.sortBy(
    lambda data: (-data[1], data[0])
)

print("Pengurutan frekuensi kata berhasil didefinisikan.")

Pengurutan frekuensi kata berhasil didefinisikan.

In [28]:
# Mengambil 10 kata dengan frekuensi kemunculan tertinggi

sepuluh_kata_teratas = rdd_kata_terurut.take(10)

print("10 KATA DENGAN FREKUENSI TERTINGGI")
print("-" * 42)

for peringkat, (kata, frekuensi) in enumerate(sepuluh_kata_teratas, start=1):
    print(f"{peringkat:2}. {kata:<15} = {frekuensi}")

10 KATA DENGAN FREKUENSI TERTINGGI
------------------------------------------
 1. dapat           = 2880
 2. yang            = 2640
 3. proses          = 1920
 4. spark           = 1920
 5. data            = 1680
 6. kata            = 1440
 7. untuk           = 1440
 8. menjadi         = 1200
 9. partition       = 1200
10. pemrosesan      = 960

In [29]:
# Menampilkan hasil Top 10 dalam bentuk tabel

import pandas as pd

tabel_top10 = pd.DataFrame(
    sepuluh_kata_teratas,
    columns=["Kata", "Frekuensi"]
)

tabel_top10.index = range(1, len(tabel_top10) + 1)
tabel_top10.index.name = "Peringkat"

display(tabel_top10)

                 Kata  Frekuensi
Peringkat
1               dapat       2880
2                yang       2640
3              proses       1920
4               spark       1920
5                data       1680
6                kata       1440
7               untuk       1440
8             menjadi       1200
9           partition       1200
10         pemrosesan        960

In [30]:
# Verifikasi jumlah hasil Top 10

jumlah_hasil_top10 = len(sepuluh_kata_teratas)

print("Jumlah kata unik        :", jumlah_kata_unik)
print("Jumlah hasil Top 10     :", jumlah_hasil_top10)

if jumlah_hasil_top10 == 10:
    print("Status : Top 10 kata berhasil diperoleh.")
else:
    print("Status : Hasil Top 10 belum sesuai.")

Jumlah kata unik        : 143
Jumlah hasil Top 10     : 10
Status : Top 10 kata berhasil diperoleh.

In [32]:
# Menyiapkan fungsi untuk menguji waktu WordCount
# pada jumlah partition yang berbeda

import time

def uji_partition(jumlah_partition):

    # Membagi ulang dataset sesuai jumlah partition yang diuji
    rdd_uji = rdd_bersih.repartition(jumlah_partition)

    # Menyimpan sementara agar proses repartition
    # tidak tercampur dengan pengukuran WordCount
    rdd_uji.cache()
    rdd_uji.count()

    waktu_mulai = time.perf_counter()

    hasil_uji = (
        rdd_uji
        .flatMap(lambda baris: baris.split())
        .map(lambda kata: (kata, 1))
        .reduceByKey(lambda a, b: a + b)
    )

    # Action untuk memicu proses Spark
    jumlah_kata_uji = hasil_uji.count()

    waktu_selesai = time.perf_counter()

    durasi = waktu_selesai - waktu_mulai

    # Membersihkan cache setelah pengujian
    rdd_uji.unpersist()

    return jumlah_kata_uji, durasi

In [33]:
# Pengujian WordCount menggunakan 1 partition

kata_unik_1, waktu_1 = uji_partition(1)

print("PENGUJIAN 1 PARTITION")
print("----------------------------")
print("Jumlah partition :", 1)
print("Kata unik        :", kata_unik_1)
print("Waktu proses     :", round(waktu_1, 4), "detik")

PENGUJIAN 1 PARTITION
----------------------------
Jumlah partition : 1
Kata unik        : 143
Waktu proses     : 0.2952 detik

In [34]:
# Pengujian WordCount menggunakan 2 partition

kata_unik_2, waktu_2 = uji_partition(2)

print("PENGUJIAN 2 PARTITION")
print("----------------------------")
print("Jumlah partition :", 2)
print("Kata unik        :", kata_unik_2)
print("Waktu proses     :", round(waktu_2, 4), "detik")

PENGUJIAN 2 PARTITION
----------------------------
Jumlah partition : 2
Kata unik        : 143
Waktu proses     : 0.4041 detik

In [35]:
# Pengujian WordCount menggunakan 4 partition

kata_unik_4, waktu_4 = uji_partition(4)

print("PENGUJIAN 4 PARTITION")
print("----------------------------")
print("Jumlah partition :", 4)
print("Kata unik        :", kata_unik_4)
print("Waktu proses     :", round(waktu_4, 4), "detik")

PENGUJIAN 4 PARTITION
----------------------------
Jumlah partition : 4
Kata unik        : 143
Waktu proses     : 0.4804 detik

In [36]:
# Pengujian WordCount menggunakan 8 partition

kata_unik_8, waktu_8 = uji_partition(8)

print("PENGUJIAN 8 PARTITION")
print("----------------------------")
print("Jumlah partition :", 8)
print("Kata unik        :", kata_unik_8)
print("Waktu proses     :", round(waktu_8, 4), "detik")

PENGUJIAN 8 PARTITION
----------------------------
Jumlah partition : 8
Kata unik        : 143
Waktu proses     : 1.0537 detik

In [37]:
# Membuat tabel perbandingan waktu proses

import pandas as pd

hasil_partition = pd.DataFrame({
    "Jumlah Partition": [1, 2, 4, 8],
    "Jumlah Kata Unik": [
        kata_unik_1,
        kata_unik_2,
        kata_unik_4,
        kata_unik_8
    ],
    "Waktu Proses (detik)": [
        waktu_1,
        waktu_2,
        waktu_4,
        waktu_8
    ]
})

hasil_partition["Waktu Proses (detik)"] = (
    hasil_partition["Waktu Proses (detik)"].round(4)
)

display(hasil_partition)

   Jumlah Partition  Jumlah Kata Unik  Waktu Proses (detik)
0                 1               143                0.2952
1                 2               143                0.4041
2                 4               143                0.4804
3                 8               143                1.0537

In [38]:
# Menentukan konfigurasi partition dengan waktu tercepat

baris_tercepat = hasil_partition.loc[
    hasil_partition["Waktu Proses (detik)"].idxmin()
]

print("HASIL PENGUJIAN TERCEPAT")
print("----------------------------")
print(
    "Jumlah partition :",
    int(baris_tercepat["Jumlah Partition"])
)
print(
    "Waktu proses     :",
    baris_tercepat["Waktu Proses (detik)"],
    "detik"
)

HASIL PENGUJIAN TERCEPAT
----------------------------
Jumlah partition : 1
Waktu proses     : 0.2952 detik

In [39]:
# Menampilkan tabel hasil pengujian tanpa index Pandas

display(
    hasil_partition.style
    .hide(axis="index")
    .set_caption("Perbandingan Waktu Pemrosesan Berdasarkan Jumlah Partition")
)

In [40]:
# Membuat pipeline WordCount khusus untuk analisis Job, Stage, dan Task

rdd_demo_6a = (
    rdd_bersih
    .flatMap(lambda baris: baris.split())
    .map(lambda kata: (kata, 1))
    .reduceByKey(lambda nilai1, nilai2: nilai1 + nilai2)
)

print("Pipeline analisis berhasil dibuat.")
print("Partition sebelum reduceByKey :", rdd_bersih.getNumPartitions())
print("Partition hasil reduceByKey   :", rdd_demo_6a.getNumPartitions())

Pipeline analisis berhasil dibuat.
Partition sebelum reduceByKey : 2
Partition hasil reduceByKey   : 2

In [41]:
# Melihat lineage atau alur ketergantungan RDD

lineage_rdd = rdd_demo_6a.toDebugString()

if isinstance(lineage_rdd, bytes):
    lineage_rdd = lineage_rdd.decode("utf-8")

print("LINEAGE RDD WORDCOUNT")
print("------------------------------")
print(lineage_rdd)

LINEAGE RDD WORDCOUNT
------------------------------
(2) PythonRDD[73] at RDD at PythonRDD.scala:57 []
 |  MapPartitionsRDD[72] at mapPartitions at PythonRDD.scala:169 []
 |  ShuffledRDD[71] at partitionBy at NativeMethodAccessorImpl.java:0 []
 +-(2) PairwiseRDD[70] at reduceByKey at /tmp/ipykernel_2287/221946432.py:7 []
    |  PythonRDD[69] at reduceByKey at /tmp/ipykernel_2287/221946432.py:7 []
    |  bigdata.txt MapPartitionsRDD[1] at textFile at NativeMethodAccessorImpl.java:0 []
    |  bigdata.txt HadoopRDD[0] at textFile at NativeMethodAccessorImpl.java:0 []

In [42]:
# Menjalankan Action untuk memicu Spark Job

sc = spark.sparkContext

nama_job = "analisis_wordcount_6a"

sc.setJobGroup(
    nama_job,
    "Analisis Job WordCount Tahap 6A"
)

hasil_wordcount_6a = rdd_demo_6a.count()

job_ids = sc.statusTracker().getJobIdsForGroup(nama_job)

print("HASIL EKSEKUSI JOB")
print("------------------------------")
print("Jumlah kata unik :", hasil_wordcount_6a)
print("Job ID           :", job_ids)

HASIL EKSEKUSI JOB
------------------------------
Jumlah kata unik : 143
Job ID           : [23]

In [7]:
# Menampilkan informasi Stage dan Task dari Job

# Memastikan sc (SparkContext) terdefinisi dari SparkSession aktif
sc = spark.sparkContext
tracker = sc.statusTracker()

# Memastikan job_ids terdefinisi dari group aktif jika sebelumnya hilang
try:
    job_ids
except NameError:
    job_ids = sc.statusTracker().getJobIdsForGroup("analisis_wordcount_6a")

print("DETAIL JOB, STAGE, DAN TASK")
print("----------------------------------------")

for job_id in job_ids:

    info_job = tracker.getJobInfo(job_id)

    if info_job is not None:

        stage_ids = list(info_job.stageIds)

        print(f"\nJob ID    : {job_id}")
        print(f"Stage ID  : {stage_ids}")
        print(f"Jumlah Stage : {len(stage_ids)}")

        for stage_id in stage_ids:

            info_stage = tracker.getStageInfo(stage_id)

            if info_stage is not None:

                print(f"\n  Stage {stage_id}")
                print(f"  Jumlah Task       : {info_stage.numTasks}")
                print(f"  Task Selesai      : {info_stage.numCompletedTasks}")
                print(f"  Task Gagal        : {info_stage.numFailedTasks}")

DETAIL JOB, STAGE, DAN TASK
----------------------------------------